### ISSUE TITLE
Launching Riot from system menu spawns new instances

### ISSUE THREAD

**Issue by ilmaisin** [flathub/im.riot.Riot#116]
At least on CentOS 7 with Gnome, opening Riot from the system menu when an instance is already running, an another instance is launched instead of focusing the existing one. The new instances don't seem to have access to the configuration files, since they always ask the user to log in again.

**Comment by SISheogorath** [comment]
What version of flatpak are you running on CentOS? Usually Riot checks for a file in temporary directory to see if an instance is already running. And in case there is one already, it should just switch to it.

There was a time where this wasn't working properly because the TMPDIR wasn't set. This was fixed by this line:

https://github.com/flathub/im.riot.Riot/blob/ef0be289f2c2d96990ff5564ac8f221fc2cfb046/im.riot.Riot.json#L125

Can you check if FLATPAK_ID is set by running `flatpak run --command=env im.riot.Riot | grep FLATPAK_ID`? That might resolves the mystery already :)

**Comment by ilmaisin** [comment]
The grep command does not seem to find anything.
```
$ flatpak run --command=env im.riot.Riot | grep FLATPAK_ID
$ flatpak --version 
Flatpak 1.0.9
```

**Comment by SISheogorath** [comment]
Then we identified the problem, have to think about a way to solve this better. Maybe using some backwards compatibility.

**Comment by Erick555** [comment]
Yeah, flatpak 1.0.9 is perhaps too ancient to support FLATPAK_I. hardcoding app name should be ok (just don't forget about it while transition to new app name).

**Comment by SISheogorath** [comment]
@ilmaisin can you check if the version from https://github.com/flathub/im.riot.Riot/pull/117 fixes the problem for you?

**Comment by ilmaisin** [comment]
> @ilmaisin can you check if the version from #117 fixes the problem for you?

I have since migrated to CentOS 8, but I can set up a VM and try.

**Comment by ilmaisin** [comment]
@SISheogorath The version from #117 does not run at all on CentOS 7. The flathub release version works fine on the same VM.

The #117 version outputs following errors on the console:

```
$ flatpak -vv run im.riot.Riot/x86_64/test
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening user flatpak installation at path /home/il/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/il/.local/share/flatpak
F: Opening user flatpak installation at path /home/il/.local/share/flatpak
F: Cleaning up unused container id 2867514768
F: Allocated instance id 1367125744
F: Allowing x11 access
F: Allowing pulseaudio access
F: Pulseaudio user configuration file '/home/il/.config/pulse/client.conf': Error opening file /home/il/.config/pulse/client.conf: Tiedostoa tai hakemistoa ei ole
F: Failed to run in transient scope: No systemd user session available, cgroups not available
F: bwrap --args 31 = --ro-bind /boot /boot --ro-bind /dev /dev --ro-bind /proc /proc --bind /run /run --ro-bind /sys /sys --ro-bind /etc /etc --ro-bind /root /root --bind /var /var --bind /tmp /tmp --ro-bind /usr /usr --symlink usr/bin /bin --symlink usr/sbin /sbin --symlink usr/lib /lib --symlink usr/lib64 /lib64 --ro-bind /home /home --ro-bind /media /media --ro-bind /mnt /mnt --ro-bind /opt /opt --ro-bind /srv /srv --bind /run/user/1000/.dbus-proxy/ /run/user/1000/.dbus-proxy/ --file 29 /.flatpak-info
F: bwrap --args 33 = --fd=32 'unix:abstract=/tmp/dbus-mOkFESYPxJ,guid=07cbaffbed5cba7f7849b6195f0f3138' /run/user/1000/.dbus-proxy/session-bus-proxy-CGAIN0 --filter '--own=im.riot.Riot.*' '--own=org.mpris.MediaPlayer2.im.riot.Riot.*' --talk=org.kde.StatusNotifierWatcher --talk=org.freedesktop.portal.Fcitx --own=org.kde.StatusNotifierItem-2-1 --talk=org.freedesktop.secrets --talk=org.freedesktop.Notifications '--call=org.freedesktop.portal.*=*' '--broadcast=org.freedesktop.portal.*=@/org/freedesktop/portal/*' 'unix:abstract=/tmp/dbus-EBpBeHwUOw,guid=74551704cad6f7442bd5da6b5f0f3138' /run/user/1000/.dbus-proxy/a11y-bus-proxy-D5SIN0 --filter --sloppy-names --call=org.a11y.atspi.Registry=org.a11y.atspi.Socket.Embed@/org/a11y/atspi/accessible/root --call=org.a11y.atspi.Registry=org.a11y.atspi.Socket.Unembed@/org/a11y/atspi/accessible/root --call=org.a11y.atspi.Registry=org.a11y.atspi.Registry.GetRegisteredEvents@/org/a11y/atspi/registry --call=org.a11y.atspi.Registry=org.a11y.atspi.DeviceEventController.GetKeystrokeListeners@/org/a11y/atspi/registry/deviceeventcontroller --call=org.a11y.atspi.Registry=org.a11y.atspi.DeviceEventController.GetDeviceEventListeners@/org/a11y/atspi/registry/deviceeventcontroller --call=org.a11y.atspi.Registry=org.a11y.atspi.DeviceEventController.NotifyListenersSync@/org/a11y/atspi/registry/deviceeventcontroller --call=org.a11y.atspi.Registry=org.a11y.atspi.DeviceEventController.NotifyListenersAsync@/org/a11y/atspi/registry/deviceeventcontroller
F: Running '/usr/libexec/flatpak-bwrap --args 31 /usr/libexec/flatpak-dbus-proxy --args=33'
F: bwrap --args 29 = --ro-bind /home/il/.local/share/flatpak/runtime/org.freedesktop.Platform/x86_64/19.08/b05888992f5d9e089bc3eb115d0b2998b394c84af1a001044844aac1b180a929/files /usr --lock-file /usr/.ref --ro-bind /home/il/.local/share/flatpak/app/im.riot.Riot/x86_64/test/d7b1f99a2b86bddb4ef69919732ada4175d7df1e7db30679cd90d254d603a322/files /app --lock-file /app/.ref --tmpfs /usr/lib/x86_64-linux-gnu/GL --ro-bind /home/il/.local/share/flatpak/runtime/org.freedesktop.Platform.GL.default/x86_64/19.08/f68c8e930d048d0490c605d992a82e11499c78cf374a67ef69fa15a4210b636b/files /usr/lib/x86_64-linux-gnu/GL/default --ro-bind /home/il/.local/share/flatpak/runtime/org.freedesktop.Platform.openh264/x86_64/2.0/73f998362a6fc0d57e0c7e83e928d32b0ec14d10d0d94291033976bdcecc6b6b/files /usr/lib/x86_64-linux-gnu/openh264 --ro-bind /home/il/.local/share/flatpak/runtime/org.freedesktop.Platform.Locale/x86_64/19.08/3bf51e44fb9105c7923a2d7a748208f2ddd1ead808205d72cc0f75b891805225-fi/files /usr/share/runtime/locale --ro-bind-data 11 /run/flatpak/ld.so.conf.d/runtime-001-org.freedesktop.Platform.GL.default.conf --symlink /usr/lib/x86_64-linux-gnu/GL/default/vulkan/icd.d/intel_icd.x86_64.json /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/intel_icd.x86_64.json --symlink /usr/lib/x86_64-linux-gnu/GL/default/vulkan/icd.d/radeon_icd.x86_64.json /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json --symlink /usr/lib/x86_64-linux-gnu/GL/default/glvnd/egl_vendor.d/50_mesa.json /usr/lib/x86_64-linux-gnu/GL/glvnd/egl_vendor.d/50_mesa.json --symlink /usr/lib/x86_64-linux-gnu/GL/default/OpenCL/vendors/mesa.icd /usr/lib/x86_64-linux-gnu/GL/OpenCL/vendors/mesa.icd --symlink /usr/lib/x86_64-linux-gnu/GL/default/lib/dri/i915_dri.so /usr/lib/x86_64-linux-gnu/GL/lib/dri/i915_dri.so --symlink /usr/lib/x86_64-linux-gnu/GL/default/lib/dri/i965_dri.so /usr/lib/x86_64-linux-gnu/GL/lib/dri/i965_dri.so --symlink /usr/lib/x86_64-linux-gnu/GL/default/lib/dri/iris_dri.so /usr/lib/x86_64-linux-gnu/GL/lib/dri/iris_dri.so --symlink /usr/lib/x86_64-linux-gnu/GL/default/lib/dri/kms_swrast_dri.so /usr/lib/x86_64-linux-gnu/GL/lib/dri/kms_swrast_dri.so --symlink /usr/lib/x86_64-linux-gnu/GL/default/lib/dri/libgallium_dri.so /usr/lib/x86_64-linux-gnu/GL/lib/dri/libgallium_dri.so --symlink /usr/lib/x86_64-linux-gnu/GL/default/lib/dri/libgallium_drv_video.so /usr/lib/x86_64-linux-gnu/GL/lib/dri/libgallium_drv_video.so --symlink /usr/lib/x86_64-linux-gnu/GL/default/lib/dri/libmesa_dri_drivers.so /usr/lib/x86_64-linux-gnu/GL/lib/dri/libmesa_dri_drivers.so --symlink /usr/lib/x86_64-linux-gnu/GL/default/lib/dri/nouveau_dri.so /usr/lib/x86_64-linux-gnu/GL/lib/dri/nouveau_dri.so --symlink /usr/lib/x86_64-linux-gnu/GL/default/lib/dri/nouveau_drv_video.so /usr/lib/x86_64-linux-gnu/GL/lib/dri/nouveau_drv_video.so --symlink /usr/lib/x86_64-linux-gnu/GL/default/lib/dri/nouveau_vieux_dri.so /usr/lib/x86_64-linux-gnu/GL/lib/dri/nouveau_vieux_dri.so --symlink /usr/lib/x86_64-linux-gnu/GL/default/lib/dri/r200_dri.so /usr/lib/x86_64-linux-gnu/GL/lib/dri/r200_dri.so --symlink /usr/lib/x86_64-linux-gnu/GL/default/lib/dri/r300_dri.so /usr/lib/x86_64-linux-gnu/GL/lib/dri/r300_dri.so --symlink /usr/lib/x86_64-linux-gnu/GL/default/lib/dri/r600_dri.so /usr/lib/x86_64-linux-gnu/GL/lib/dri/r600_dri.so --symlink /usr/lib/x86_64-linux-gnu/GL/default/lib/dri/r600_drv_video.so /usr/lib/x86_64-linux-gnu/GL/lib/dri/r600_drv_video.so --symlink /usr/lib/x86_64-linux-gnu/GL/default/lib/dri/radeon_dri.so /usr/lib/x86_64-linux-gnu/GL/lib/dri/radeon_dri.so --symlink /usr/lib/x86_64-linux-gnu/GL/default/lib/dri/radeonsi_dri.so /usr/lib/x86_64-linux-gnu/GL/lib/dri/radeonsi_dri.so --symlink /usr/lib/x86_64-linux-gnu/GL/default/lib/dri/radeonsi_drv_video.so /usr/lib/x86_64-linux-gnu/GL/lib/dri/radeonsi_drv_video.so --symlink /usr/lib/x86_64-linux-gnu/GL/default/lib/dri/swrast_dri.so /usr/lib/x86_64-linux-gnu/GL/lib/dri/swrast_dri.so --symlink /usr/lib/x86_64-linux-gnu/GL/default/lib/dri/virtio_gpu_dri.so /usr/lib/x86_64-linux-gnu/GL/lib/dri/virtio_gpu_dri.so --symlink /usr/lib/x86_64-linux-gnu/GL/default/lib/dri/vmwgfx_dri.so /usr/lib/x86_64-linux-gnu/GL/lib/dri/vmwgfx_dri.so --symlink /usr/lib/x86_64-linux-gnu/GL/default/lib/d3d/d3dadapter9.so.1 /usr/lib/x86_64-linux-gnu/GL/lib/d3d/d3dadapter9.so.1 --symlink /usr/lib/x86_64-linux-gnu/GL/default/lib/d3d/d3dadapter9.so.1.0.0 /usr/lib/x86_64-linux-gnu/GL/lib/d3d/d3dadapter9.so.1.0.0 --symlink /usr/lib/x86_64-linux-gnu/GL/default/vulkan/explicit_layer.d/VkLayer_MESA_overlay.json /usr/lib/x86_64-linux-gnu/GL/vulkan/explicit_layer.d/VkLayer_MESA_overlay.json --ro-bind-data 12 /run/flatpak/ld.so.conf.d/runtime-002-org.freedesktop.Platform.openh264.conf --proc /proc --unshare-pid --dir /tmp --dir /var/tmp --dir /run/host --dir /run/user/1000 --setenv XDG_RUNTIME_DIR /run/user/1000 --symlink ../run /var/run --ro-bind /sys/block /sys/block --ro-bind /sys/bus /sys/bus --ro-bind /sys/class /sys/class --ro-bind /sys/dev /sys/dev --ro-bind /sys/devices /sys/devices --symlink /etc/timezone /var/db/zoneinfo --ro-bind-data 14 /etc/passwd --ro-bind-data 15 /etc/group --ro-bind-data 16 /etc/pkcs11/pkcs11.conf --ro-bind /etc/machine-id /etc/machine-id --ro-bind /home/il/.local/share/flatpak/runtime/org.freedesktop.Platform/x86_64/19.08/b05888992f5d9e089bc3eb115d0b2998b394c84af1a001044844aac1b180a929/files/etc/ca-certificates.conf /etc/ca-certificates.conf --ro-bind /home/il/.local/share/flatpak/runtime/org.freedesktop.Platform/x86_64/19.08/b05888992f5d9e089bc3eb115d0b2998b394c84af1a001044844aac1b180a929/files/etc/e2scrub.conf /etc/e2scrub.conf --ro-bind /home/il/.local/share/flatpak/runtime/org.freedesktop.Platform/x86_64/19.08/b05888992f5d9e089bc3eb115d0b2998b394c84af1a001044844aac1b180a929/files/etc/issue /etc/issue --ro-bind /home/il/.local/share/flatpak/runtime/org.freedesktop.Platform/x86_64/19.08/b05888992f5d9e089bc3eb115d0b2998b394c84af1a001044844aac1b180a929/files/etc/issue.net /etc/issue.net --ro-bind /home/il/.local/share/flatpak/runtime/org.freedesktop.Platform/x86_64/19.08/b05888992f5d9e089bc3eb115d0b2998b394c84af1a001044844aac1b180a929/files/etc/ld.so.conf /etc/ld.so.conf --ro-bind /home/il/.local/share/flatpak/runtime/org.freedesktop.Platform/x86_64/19.08/b05888992f5d9e089bc3eb115d0b2998b394c84af1a001044844aac1b180a929/files/etc/mke2fs.conf /etc/mke2fs.conf --ro-bind /home/il/.local/share/flatpak/runtime/org.freedesktop.Platform/x86_64/19.08/b05888992f5d9e089bc3eb115d0b2998b394c84af1a001044844aac1b180a929/files/etc/moduli /etc/moduli --symlink ../../proc/self/mounts /etc/mtab --ro-bind /home/il/.local/share/flatpak/runtime/org.freedesktop.Platform/x86_64/19.08/b05888992f5d9e089bc3eb115d0b2998b394c84af1a001044844aac1b180a929/files/etc/nsswitch.conf /etc/nsswitch.conf --symlink ../usr/lib/os-release /etc/os-release --ro-bind /home/il/.local/share/flatpak/runtime/org.freedesktop.Platform/x86_64/19.08/b05888992f5d9e089bc3eb115d0b2998b394c84af1a001044844aac1b180a929/files/etc/protocols /etc/protocols --ro-bind /home/il/.local/share/flatpak/runtime/org.freedesktop.Platform/x86_64/19.08/b05888992f5d9e089bc3eb115d0b2998b394c84af1a001044844aac1b180a929/files/etc/rpc /etc/rpc --ro-bind /home/il/.local/share/flatpak/runtime/org.freedesktop.Platform/x86_64/19.08/b05888992f5d9e089bc3eb115d0b2998b394c84af1a001044844aac1b180a929/files/etc/services /etc/services --ro-bind /home/il/.local/share/flatpak/runtime/org.freedesktop.Platform/x86_64/19.08/b05888992f5d9e089bc3eb115d0b2998b394c84af1a001044844aac1b180a929/files/etc/ssh_config /etc/ssh_config --ro-bind /home/il/.local/share/flatpak/runtime/org.freedesktop.Platform/x86_64/19.08/b05888992f5d9e089bc3eb115d0b2998b394c84af1a001044844aac1b180a929/files/etc/vdpau_wrapper.cfg /etc/vdpau_wrapper.cfg --ro-bind /home/il/.local/share/flatpak/runtime/org.freedesktop.Platform/x86_64/19.08/b05888992f5d9e089bc3eb115d0b2998b394c84af1a001044844aac1b180a929/files/etc/xattr.conf /etc/xattr.conf --ro-bind /home/il/.local/share/flatpak/runtime/org.freedesktop.Platform/x86_64/19.08/b05888992f5d9e089bc3eb115d0b2998b394c84af1a001044844aac1b180a929/files/etc/alsa /etc/alsa --ro-bind /home/il/.local/share/flatpak/runtime/org.freedesktop.Platform/x86_64/19.08/b05888992f5d9e089bc3eb115d0b2998b394c84af1a001044844aac1b180a929/files/etc/dbus-1 /etc/dbus-1 --ro-bind /home/il/.local/share/flatpak/runtime/org.freedesktop.Platform/x86_64/19.08/b05888992f5d9e089bc3eb115d0b2998b394c84af1a001044844aac1b180a929/files/etc/fonts /etc/fonts --ro-bind /home/il/.local/share/flatpak/runtime/org.freedesktop.Platform/x86_64/19.08/b05888992f5d9e089bc3eb115d0b2998b394c84af1a001044844aac1b180a929/files/etc/geoclue /etc/geoclue --ro-bind /home/il/.local/share/flatpak/runtime/org.freedesktop.Platform/x86_64/19.08/b05888992f5d9e089bc3eb115d0b2998b394c84af1a001044844aac1b180a929/files/etc/gtk-3.0 /etc/gtk-3.0 --ro-bind /home/il/.local/share/flatpak/runtime/org.freedesktop.Platform/x86_64/19.08/b05888992f5d9e089bc3eb115d0b2998b394c84af1a001044844aac1b180a929/files/etc/profile.d /etc/profile.d --ro-bind /home/il/.local/share/flatpak/runtime/org.freedesktop.Platform/x86_64/19.08/b05888992f5d9e089bc3eb115d0b2998b394c84af1a001044844aac1b180a929/files/etc/pulse /etc/pulse --ro-bind /home/il/.local/share/flatpak/runtime/org.freedesktop.Platform/x86_64/19.08/b05888992f5d9e089bc3eb115d0b2998b394c84af1a001044844aac1b180a929/files/etc/ssl /etc/ssl --ro-bind /home/il/.local/share/flatpak/runtime/org.freedesktop.Platform/x86_64/19.08/b05888992f5d9e089bc3eb115d0b2998b394c84af1a001044844aac1b180a929/files/etc/xdg /etc/xdg --bind /home/il/.var/app/im.riot.Riot/cache /var/cache --bind /home/il/.var/app/im.riot.Riot/data /var/data --bind /home/il/.var/app/im.riot.Riot/config /var/config --bind /home/il/.var/app/im.riot.Riot/cache/tmp /var/tmp --symlink usr/lib /lib --symlink usr/lib64 /lib64 --symlink usr/bin /bin --symlink usr/sbin /sbin --seccomp 17 --ro-bind /run/user/1000/.flatpak-helper/monitor /run/host/monitor --symlink /run/host/monitor/localtime /etc/localtime --symlink /run/host/monitor/resolv.conf /etc/resolv.conf --symlink /run/host/monitor/host.conf /etc/host.conf --symlink /run/host/monitor/hosts /etc/hosts --symlink /run/host/monitor/timezone /etc/timezone --ro-bind-data 22 /etc/ld.so.conf --ro-bind-data 13 /etc/ld.so.cache --ro-bind /run/user/1000/.flatpak/1367125744 /run/user/1000/.flatpak/1367125744 --lock-file /run/user/1000/.flatpak/1367125744/.ref --file 23 /.flatpak-info --ro-bind-data 24 /.flatpak-info --symlink ../../../.flatpak-info /run/user/1000/flatpak-info --info-fd 25 --bind /run/user/1000/doc/by-app/im.riot.Riot /run/user/1000/doc --dev-bind /dev /dev --tmpfs /dev/shm --bind /run/user/1000/app/im.riot.Riot /run/user/1000/app/im.riot.Riot --dir /home/il --dir /home/il/.local/share/flatpak --dir /home/il/.var/app --bind /home/il/.var/app/im.riot.Riot /home/il/.var/app/im.riot.Riot --bind /home/il/Lataukset /home/il/Lataukset --bind /run/user/1000/keyring /run/user/1000/keyring --ro-bind-data 26 /home/il/.var/app/im.riot.Riot/config/user-dirs.dirs --tmpfs /tmp/.X11-unix --ro-bind /tmp/.X11-unix/X0 /tmp/.X11-unix/X99 --ro-bind-data 28 /run/user/1000/Xauthority --ro-bind-data 27 /run/user/1000/pulse/config --bind /run/user/1000/pulse/native /run/user/1000/pulse/native --bind /run/user/1000/.dbus-proxy/session-bus-proxy-CGAIN0 /run/user/1000/bus --bind /run/user/1000/.dbus-proxy/a11y-bus-proxy-D5SIN0 /run/user/1000/at-spi-bus --sync-fd 30 --bind /run/systemd/journal/socket /run/systemd/journal/socket --bind /run/systemd/journal/stdout /run/systemd/journal/stdout --ro-bind /usr/share/fonts /run/host/fonts --ro-bind /usr/lib/fontconfig/cache /run/host/fonts-cache --ro-bind /home/il/.cache/fontconfig /run/host/user-fonts-cache --ro-bind /usr/share/icons /run/host/share/icons --symlink /app/lib/debug/source /run/build --symlink /usr/lib/debug/source /run/build-runtime
F: Running '/usr/libexec/flatpak-bwrap --args 29 riot'
Keytar unexpected error: Error: ENOENT, node_modules/keytar/build/Release/keytar.node not found in /app/Riot/resources/app.asar
    at createError (electron/js2c/asar.js:111:17)
    at Object.func [as .node] (electron/js2c/asar.js:146:27)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/app/Riot/resources/app.asar/node_modules/keytar/lib/keytar.js:1:14)
    at Module._compile (internal/modules/cjs/loader.js:967:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1004:10) {
  code: 'ENOENT',
  errno: -2
}
Seshat unexpected error: Error: ENOENT, node_modules/matrix-seshat/native/index.node not found in /app/Riot/resources/app.asar
    at createError (electron/js2c/asar.js:111:17)
    at Object.func [as .node] (electron/js2c/asar.js:146:27)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/app/Riot/resources/app.asar/node_modules/matrix-seshat/lib/index.js:15:16)
    at Module._compile (internal/modules/cjs/loader.js:967:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1004:10) {
  code: 'ENOENT',
  errno: -2
}
Other instance detected: exiting
[fake-sandbox: zypak-sandbox] No data could be read (host died?)
[fake-sandbox: zypak-sandbox] Quitting Zygote...
```

**Comment by SISheogorath** [comment]
Is there already an instance running? Maybe minimized?

**Comment by ilmaisin** [comment]
> Is there already an instance running? Maybe minimized? Can you use `flatpak kill im.riot.Riot` and retry?

It does not seem to be so. 1.0.9 seems to lack the kill option, but I am not running any "riot-desktop" processes either.
