### ISSUE TITLE
Startup failure since last update

### ISSUE THREAD

**Issue by akallabeth** [flathub/im.riot.Riot#229]
I can no longer use element on my debian 11 machine from flathub:
```
 flatpak run im.riot.Riot 
[2 preload-host-spawn-strategy] Running: /app/bin/zypak-helper child - /app/Element/element-desktop --type=zygote
/home/nin/.var/app/im.riot.Riot/config/Element exists: yes
/home/nin/.var/app/im.riot.Riot/config/Riot exists: yes
Gtk-Message: 15:21:03.857: Failed to load module "canberra-gtk-module"
Gtk-Message: 15:21:03.857: Failed to load module "canberra-gtk-module"
Starting auto update with base URL: https://packages.element.io/desktop/update/
Auto update not supported on this platform
Fetching translation json for locale: en_EN
Changing application language to en-us
Fetching translation json for locale: en-us
Could not fetch translation json for locale: 'en-us' Error: Cannot find module './i18n/strings/en-us.json'
Require stack:
- /app/Element/resources/app.asar/lib/language-helper.js
- /app/Element/resources/app.asar/lib/tray.js
- /app/Element/resources/app.asar/lib/electron-main.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:887:15)
    at Function.n._resolveFilename (electron/js2c/browser_init.js:257:1128)
    at Module._load (internal/modules/cjs/loader.js:732:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at AppLocalization.fetchTranslationJson (/app/Element/resources/app.asar/lib/language-helper.js:76:20)
    at /app/Element/resources/app.asar/lib/language-helper.js:89:39
    at Array.forEach (<anonymous>)
    at AppLocalization.setAppLocale (/app/Element/resources/app.asar/lib/language-helper.js:88:17) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/app/Element/resources/app.asar/lib/language-helper.js',
    '/app/Element/resources/app.asar/lib/tray.js',
    '/app/Element/resources/app.asar/lib/electron-main.js',
    undefined
  ]
}
Resetting the UI components after locale change
Resetting the UI components after locale change
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
Changing application language to en-us
Fetching translation json for locale: en-us
Could not fetch translation json for locale: 'en-us' Error: Cannot find module './i18n/strings/en-us.json'
Require stack:
- /app/Element/resources/app.asar/lib/language-helper.js
- /app/Element/resources/app.asar/lib/tray.js
- /app/Element/resources/app.asar/lib/electron-main.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:887:15)
    at Function.n._resolveFilename (electron/js2c/browser_init.js:257:1128)
    at Module._load (internal/modules/cjs/loader.js:732:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at AppLocalization.fetchTranslationJson (/app/Element/resources/app.asar/lib/language-helper.js:76:20)
    at /app/Element/resources/app.asar/lib/language-helper.js:89:39
    at Array.forEach (<anonymous>)
    at AppLocalization.setAppLocale (/app/Element/resources/app.asar/lib/language-helper.js:88:17) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/app/Element/resources/app.asar/lib/language-helper.js',
    '/app/Element/resources/app.asar/lib/tray.js',
    '/app/Element/resources/app.asar/lib/electron-main.js',
    undefined
  ]
}
Resetting the UI components after locale change
```

1. This happens also on newly created user accounts (tested to rule out some configuration problem)
2. The element fork `SchildiChat`does run on the same machine without this glitch.
![Screenshot from 2021-11-04 15-24-33](https://user-images.githubusercontent.com/3472254/140331400-bb0e6abd-9b31-477b-9539-2453ee184370.png)

**Comment by 3699n** [comment]
I'm experiencing the same issue.

**Comment by akallabeth** [comment]
It may be related to this issue I´ve found: https://github.com/flatpak/flatpak/issues/4559

**Comment by 3699n** [comment]
As far as I am aware, it is these issues [vector-im/element-web#19169](https://github.com/vector-im/element-web/issues/19169), [vector-im/element-web#19218](https://github.com/vector-im/element-web/issues/19218), and [vector-im/element-web#19153](https://github.com/vector-im/element-web/issues/19153)

**Comment by akallabeth** [comment]
@3699n oh. I´ve just experienced a few flatpak apps failing network due to the aforementioned bug and thought it might be related (since this one also uses the affected runtime)
