### ISSUE TITLE
Element Goes Offline On Startup And Doesn't Work Correctly Until I Re-Login

### ISSUE THREAD

**Issue by VihagChaturvedi** [flathub/im.riot.Riot#247]
[log-1.log](https://github.com/flathub/im.riot.Riot/files/7874784/log-1.log)

This is the log generated by Element on startup

One of the lines caught my eye

`M_MISSING_TOKEN: Invalid Authorization header.`

What can I do to mitigate this issue?

Thanks!

**Comment by TheLastProject** [comment]
I have the exact same issue and my logs are very very similar. Containing all the same notes as you:
```
2022-03-07T16:32:59.463Z I Failed to check for protocol support: will retry Invalid Authorization header.
M_MISSING_TOKEN: Invalid Authorization header.
    at E (vector://vector/webapp/bundles/069fd4d72f624a5a90be/vendors~init.js:2:637207)
    at vector://vector/webapp/bundles/069fd4d72f624a5a90be/vendors~init.js:2:636610
    at Object.callback (vector://vector/webapp/bundles/069fd4d72f624a5a90be/vendors~init.js:2:636173)
    at vector://vector/webapp/bundles/069fd4d72f624a5a90be/vendors~init.js:2:28999
    at XMLHttpRequest.i.onreadystatechange (vector://vector/webapp/bundles/069fd4d72f624a5a90be/vendors~init.js:2:29023)
2022-03-07T16:33:00.454Z I EventIndex: Error initializing the event index {"message":"Error opening the database: DatabaseUnlockError(\"Invalid passphrase\")"}
```

```
2022-03-07T16:33:02.210Z I Crypto: initialising Olm device...
2022-03-07T16:33:02.222Z W Unable to initialise e2e OLM.BAD_ACCOUNT_KEY
Error: OLM.BAD_ACCOUNT_KEY
    at vector://vector/webapp/bundles/069fd4d72f624a5a90be/vendors~init.js:2:4061364
    at Ce.<anonymous> (vector://vector/webapp/bundles/069fd4d72f624a5a90be/vendors~init.js:2:4064243)
    at Ce.unpickle (vector://vector/webapp/bundles/069fd4d72f624a5a90be/vendors~init.js:2:4061070)
    at vector://vector/webapp/bundles/069fd4d72f624a5a90be/vendors~init.js:2:2068532
    at IDBRequest.n.onsuccess (vector://vector/webapp/bundles/069fd4d72f624a5a90be/vendors~init.js:2:4231755)
```

**Comment by SISheogorath** [comment]
Let's link this to an upstream issue: https://github.com/vector-im/element-web/issues/18584

It seems, this might not be flatpak specific.

**Comment by TheLastProject** [comment]
Well, I can confirm it never happened to me on taw's RPM (copr repo) but given that one stopped getting updated I can't completely exclude it being a version difference thing. Is there some way I can run a specific version of this Flatpak to confirm if the issue is packaging-specific or version-specific for me?

**Comment by joshlupo** [comment]
Any update on this issue? I'm still experiencing the same on Manjaro linux.
I have to log out and back in on every reboot but then it works.
