### ISSUE TITLE
Unable to launch Element

### ISSUE THREAD

**Issue by TheEvilSkeleton** [flathub/im.riot.Riot#290]
Since https://github.com/flathub/im.riot.Riot/commit/e71df6d1c84f8d96ed787675f3e74390febca4bc, I am unable to launch Element. When running in the terminal, I get this error:
```
❯ flatpak run im.riot.Riot
/var/home/TheEvilSkeleton/.var/app/im.riot.Riot/config/Element exists: yes
/var/home/TheEvilSkeleton/.var/app/im.riot.Riot/config/Riot exists: no
LaunchProcess: failed to execvp:
xdg-settings
Gtk-Message: 22:20:49.556: Failed to load module "canberra-gtk-module"
Gtk-Message: 22:20:49.556: Failed to load module "canberra-gtk-module"
[3:0831/222049.580285:ERROR:bus.cc(398)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[3:0831/222049.580389:ERROR:bus.cc(398)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
Couldn't find webapp files in any of: 
	/app/Element/resources/app.asar/webapp.asar
	/app/Element/resources/webapp.asar
	/app/Element/resources/app.asar/webapp
	/app/Element/resources/webapp
App setup failed: exiting Error: Failed to find webapp files
    at /app/Element/resources/app.asar/lib/electron-main.js:145:15
    at Generator.throw (<anonymous>)
    at rejected (/app/Element/resources/app.asar/lib/electron-main.js:43:65)
```

Downgrading to the previous commit made it work again:
```
flatpak update --user --commit=aaff316cf359cfae76dc95c03df9841ecaee29bde522d38b1f5bddc38fc6f7e1 im.riot.Riot
```

I'm using Fedora 37 Silverblue on Wayland.

**Comment by SISheogorath** [comment]
I think the commit you have linked is the wrong one. There were 2 releases yesterday, you linked the second one, but that has the following OSTree commit: `a12ceea95a7a2c0a69b0a4d07f3c963a4cc9adf55de041a2ebc0322a908e3dfd`

`7028d5f94f98005684c0e9943dc9421ad14d3c0645e7ad5a960c71c489a4d97d` is the parent commit, which has the issue you mentioned, as pointed out in the linked issue from upstream https://github.com/vector-im/element-web/issues/23177

**Comment by eternaltyro** [comment]
This happened to me today with v1.11.24 - 

```
Element version: 1.11.24
Olm version: 3.2.12
```

Flatpak info:

```
Element - Create, share, communicate, chat and call securely, and bridge to
other apps

          ID: im.riot.Riot
         Ref: app/im.riot.Riot/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 1.11.24
     License: Apache-2.0
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 301.5 MB
     Runtime: org.freedesktop.Platform/x86_64/22.08
         Sdk: org.freedesktop.Sdk/x86_64/22.08

      Commit: 33a595252d302821f56ab0de783334273df3a4d317c70884a8444c925628ce34
      Parent: 5ac3b09697d656fe3b4ff88e5f26bdca532f7e01cc2c94b0197f7e5700510623
     Subject: fix: Add workaround to disable broken search (40ff7a3c)
        Date: 2023-03-07 19:57:48 +0000
```

When I run `flatpak run im.riot.Riot` : 

```
[3:0313/203426.833233:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
/home/eternaltyro/.var/app/im.riot.Riot/config/Element exists: yes
/home/eternaltyro/.var/app/im.riot.Riot/config/Riot exists: no
LaunchProcess: failed to execvp:
xdg-settings
[3:0313/203428.159189:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[3:0313/203428.159251:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
Starting auto update with base URL: https://packages.element.io/desktop/update/
Auto update not supported on this platform
[52:0313/203428.243063:ERROR:gpu_init.cc(523)] Passthrough is not supported, GL is egl, ANGLE is 
Fetching translation json for locale: en_EN
Changing application language to en
Fetching translation json for locale: en
Resetting the UI components after locale change
Resetting the UI components after locale change
Changing application language to en
Fetching translation json for locale: en
Resetting the UI components after locale change
```

**Comment by msylw** [comment]
This is old, but still open and maybe someone stumbles on it (like me):

I had this issue as well, managed to get element with visible window by starting it with `--disable-gpu`:
```
flatpak run im.riot.Riot --disable-gpu
```

OS: Ubuntu 24.10, Plasma on Wayland
GPU: Radeon RX 580
