### ISSUE TITLE
Element crashes with SIGILL

### ISSUE THREAD

**Issue by charmoniumQ** [flathub/im.riot.Riot#360]
I don't know how to debug this crash. The Flatpak documentation says something about `flatpak run --devel ...`. Inside that container, I change `zypak-wrapper $args` to `gdb zypak-wrapper --args $args` in the runner script. Then I run the code, continue past the debug breakpoint, let it crash, and then collect the backtrace. However, this is not very informative. How do I debug this further?

# Debug steps

```
$ flatpak run --devel --command=sh im.riot.Riot
[📦 im.riot.Riot ~]$ sed 's/zypak-wrapper/gdb --quiet zypak-wrapper --args/' $(which element) > element-debug
[📦 im.riot.Riot ~]$ chmod +x element-debug
[📦 im.riot.Riot ~]$ ./element-debug
Reading symbols from /app/Element/element-desktop...
(No debugging symbols found in /app/Element/element-desktop)
(gdb) run
Starting program: /app/Element/element-desktop --enable-features=WebRTCPipeWireCapturer
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff4607640 (LWP 119)]
[Detaching after fork from child process 120]
[116:0421/120701.259984:FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /app/Element/chrome-sandbox is owned by root and has mode 4755.

Thread 1 "element-desktop" received signal SIGTRAP, Trace/breakpoint trap.
0x000055555ab3a1c5 in ?? ()
(gdb) continue
Continuing.

Thread 1 "element-desktop" received signal SIGILL, Illegal instruction.
0x000055555ab3a1c5 in ?? ()
(gdb) backtrace
#0  0x000055555ab3a1c5 in  ()
#1  0x00007fffffffcd18 in  ()
#2  0x0000000000000115 in  ()
#3  0x00007fffffffc8e0 in  ()
#4  0x00007fffffffce88 in  ()
#5  0x00007fffffffce80 in  ()
#6  0xfffffffffffffe38 in  ()
#7  0x0000000000000121 in  ()
#8  0x0000000000000116 in  ()
#9  0x00003e000025c780 in  ()
#10 0x0000000000000116 in  ()
#11 0x3234303a3631315b in  ()
#12 0x3130373032312f31 in  ()
#13 0x3a3438393935322e in  ()
#14 0x65733a4c41544146 in  ()
#15 0x6e61735f64697574 in  ()
#16 0x736f685f786f6264 in  ()
#17 0x3835312863632e74 in  ()
#18 0x5320656854205d29 in  ()
#19 0x646e617320444955 in  ()
#20 0x706c656820786f62 in  ()
#21 0x72616e6962207265 in  ()
#22 0x6f66207361772079 in  ()
#23 0x747562202c646e75 in  ()
#24 0x20746f6e20736920 in  ()
#25 0x72756769666e6f63 in  ()
#26 0x6572726f63206465 in  ()
#27 0x6152202e796c7463 in  ()
#28 0x6168742072656874 in  ()
#29 0x6977206e7572206e in  ()
#30 0x61732074756f6874 in  ()
#31 0x676e69786f62646e in  ()
#32 0x6f6261206d274920 in  ()
#33 0x6f6e20676e697472 in  ()
#34 0x6e20756f59202e77 in  ()
#35 0x6d206f7420646565 in  ()
#36 0x6572757320656b61 in  ()
#37 0x612f207461687420 in  ()
#38 0x656d656c452f7070 in  ()
#39 0x6d6f7268632f746e in  ()
#40 0x6f62646e61732d65 in  ()
#41 0x6e776f2073692078 in  ()
#42 0x6f72207962206465 in  ()
#43 0x6820646e6120746f in  ()
#44 0x2065646f6d207361 in  ()
#45 0xaa000a2e35353734 in  ()
frames between #46 and #137 are 0xaaa..., so I removed them.
#137 0xaaaaaaaaaaaaaaaa in  ()
#138 0xaaaaaaaaaaaaaaaa in  ()
#139 0x00007fffffffcdb0 in  ()
#140 0x0000000000000101 in  ()
#141 0x00000000000000f7 in  ()
#142 0x00003e0000214900 in  ()
#143 0x000000006442c2b5 in  ()
#144 0x00007fffffffce80 in  ()
#145 0x00007fffffffcef0 in  ()
#146 0x00005555566a6459 in  ()
#147 0x00007fffffffce88 in  ()
#148 0x00007fffffffce80 in  ()
#149 0x00007fffffffcdb0 in  ()
#150 0x00005555577e8986 in  ()
#151 0xaaaaaaaaaaaaaa01 in  ()
#152 0x00007fffffffce80 in  ()
#153 0x00003e0000298130 in  ()
#154 0x0000009e0000009e in  ()
#155 0xcb33fa60409e9200 in  ()
#156 0x00007fffffffd1b0 in  ()
#157 0x00000000ffffff00 in  ()
#158 0x00003e000026e300 in  ()
#159 0x00007fffffffce51 in  ()
#160 0x00007fffffffce70 in  ()
#161 0x00007fffffffcfc0 in  ()
#162 0x000055555c0c5bcf in  ()
#163 0x000000000000fd01 in  ()
#164 0x000000000011123c in  ()
#165 0x0000000000000002 in  ()
#166 0x0000fffe000081ed in  ()
#167 0x000000000000fffe in  ()
#168 0x0000000000000000 in  ()
(gdb) 
quit
A debugging session is active.

        Inferior 1 [process 116] will be killed.

Quit anyway? (y or n) y
```

# Riot/Element version

```
$ flatpak info im.riot.Riot                               

Element - Create, share, communicate, chat and call securely, and bridge to
other apps

          ID: im.riot.Riot
         Ref: app/im.riot.Riot/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 1.11.29
     License: Apache-2.0
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 362.1 MB
     Runtime: org.freedesktop.Platform/x86_64/22.08
         Sdk: org.freedesktop.Sdk/x86_64/22.08

      Commit: 4bdcc0ac38196e00345da3f2b572a444fc41c0f6d291fa43d6b634c1141a3b83
      Parent: 710c4a54700b7d82ca5fec116ed1d31104e23f2502935ff068a11843aa2d9523
     Subject: Update element-desktop_1.11.28_amd64.deb to 1.11.29 (ff59f1ac)
        Date: 2023-04-12 16:34:10 +0000
```

# Linux kernel version

```
$ uname --all
Linux laptop 5.15.0-72-generic #79-Ubuntu SMP Wed Apr 19 08:22:18 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

# Ubuntu version

```
$ lsb_release --all
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.2 LTS
Release:        22.04
Codename:       jammy
```

# CPU info

```
$ lscpu         
Architecture:            x86_64
  CPU op-mode(s):        32-bit, 64-bit
  Address sizes:         39 bits physical, 48 bits virtual
  Byte Order:            Little Endian
CPU(s):                  4
  On-line CPU(s) list:   0-3
Vendor ID:               GenuineIntel
  Model name:            Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
    CPU family:          6
    Model:               78
    Thread(s) per core:  2
    Core(s) per socket:  2
    Socket(s):           1
    Stepping:            3
    CPU max MHz:         2800.0000
    CPU min MHz:         400.0000
    BogoMIPS:            4800.00
    Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdts
                         cp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est t
                         m2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch 
                         cpuid_fault epb invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust sgx bmi1 avx2 smep bmi
                         2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp
                         _epp md_clear flush_l1d arch_capabilities
Virtualization features: 
  Virtualization:        VT-x
Caches (sum of all):     
  L1d:                   64 KiB (2 instances)
  L1i:                   64 KiB (2 instances)
  L2:                    512 KiB (2 instances)
  L3:                    3 MiB (1 instance)
NUMA:                    
  NUMA node(s):          1
  NUMA node0 CPU(s):     0-3
Vulnerabilities:         
  Itlb multihit:         KVM: Mitigation: VMX disabled
  L1tf:                  Mitigation; PTE Inversion; VMX conditional cache flushes, SMT vulnerable
  Mds:                   Mitigation; Clear CPU buffers; SMT vulnerable
  Meltdown:              Mitigation; PTI
  Mmio stale data:       Mitigation; Clear CPU buffers; SMT vulnerable
  Retbleed:              Mitigation; IBRS
  Spec store bypass:     Mitigation; Speculative Store Bypass disabled via prctl and seccomp
  Spectre v1:            Mitigation; usercopy/swapgs barriers and __user pointer sanitization
  Spectre v2:            Mitigation; IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS Not affected
  Srbds:                 Mitigation; Microcode
  Tsx async abort:       Not affected
```

**Comment by SISheogorath** [comment]
This should also be resolved by #357. Feel free to reopen if it still persists.
