### ISSUE TITLE
Element Flatpak doesnt start

### ISSUE THREAD

**Issue by corincorvus** [flathub/im.riot.Riot#456]
Hi,

i cant start Element Flatpak on Nobara Linux on my Desktop PC. On my Laptop, with the same OS and Versions i can (installed with the same usb stick).

OS: Nobara Linux Fedora 39
Version of Element: Flatpack 1.11.69

All Updates are Done, language packs are installed. 

Crash Log:
```
Jul  2 19:12:17 C-I systemd[1737]: Started app-im.riot.Riot-bb4822426eb54529b02aedc7ab01e65a.scope - Element.
Jul  2 19:12:17 C-I systemd[1737]: Started app-flatpak-im.riot.Riot-9844.scope.
Jul  2 19:12:17 C-I systemd[1737]: Started app-flatpak-im.riot.Riot-9872.scope.
Jul  2 19:12:17 C-I plasmashell[9858]: [3:0702/191217.925504:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: Datei oder Verzeichnis nicht gefunden
Jul  2 19:12:18 C-I plasmashell[9858]: /home/corin/.var/app/im.riot.Riot/config/Element exists: yes
Jul  2 19:12:18 C-I plasmashell[9858]: /home/corin/.var/app/im.riot.Riot/config/Riot exists: no
Jul  2 19:12:18 C-I plasmashell[9902]: LaunchProcess: failed to execvp:
Jul  2 19:12:18 C-I plasmashell[9902]: xdg-settings
Jul  2 19:12:18 C-I plasmashell[9904]: LaunchProcess: failed to execvp:
Jul  2 19:12:18 C-I plasmashell[9904]: xdg-settings
Jul  2 19:12:18 C-I plasmashell[9858]: [3:0702/191218.160230:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: Datei oder Verzeichnis nicht gefunden
Jul  2 19:12:18 C-I plasmashell[9858]: [3:0702/191218.160256:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: Datei oder Verzeichnis nicht gefunden
Jul  2 19:12:18 C-I plasmashell[9858]: [3:0702/191218.172130:ERROR:object_proxy.cc(576)] Failed to call method: org.kde.KWallet.isEnabled: object_path= /modules/kwalletd6: org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown
Jul  2 19:12:18 C-I plasmashell[9858]: [3:0702/191218.172142:ERROR:kwallet_dbus.cc(112)] Error contacting kwalletd6 (isEnabled)
Jul  2 19:12:18 C-I plasmashell[9858]: [3:0702/191218.172235:ERROR:object_proxy.cc(576)] Failed to call method: org.kde.KLauncher.start_service_by_desktop_name: object_path= /KLauncher: org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown
Jul  2 19:12:18 C-I plasmashell[9858]: [3:0702/191218.172243:ERROR:kwallet_dbus.cc(81)] Error contacting klauncher to start kwalletd6
Jul  2 19:12:18 C-I plasmashell[9858]: [3:0702/191218.172318:ERROR:object_proxy.cc(576)] Failed to call method: org.kde.KWallet.close: object_path= /modules/kwalletd6: org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown
Jul  2 19:12:18 C-I plasmashell[9858]: [3:0702/191218.172323:ERROR:kwallet_dbus.cc(502)] Error contacting kwalletd6 (close)
Jul  2 19:12:18 C-I plasmashell[9858]: Starting auto update with base URL: https://packages.element.io/desktop/update/
Jul  2 19:12:18 C-I plasmashell[9858]: Auto update not supported on this platform
Jul  2 19:12:18 C-I plasmashell[9858]: Fetching translation json for locale: en_EN
Jul  2 19:12:18 C-I plasmashell[9858]: Changing application language to de
Jul  2 19:12:18 C-I plasmashell[9858]: Fetching translation json for locale: de
Jul  2 19:12:18 C-I plasmashell[9858]: Could not fetch translation json for locale: 'de' Error: ENOENT, lib/i18n/strings/de.json not found in /app/Element/resources/app.asar
Jul  2 19:12:18 C-I plasmashell[9858]:    at createError (node:electron/js2c/node_init:2:1657)
Jul  2 19:12:18 C-I plasmashell[9858]:    at t.readFileSync (node:electron/js2c/node_init:2:9941)
Jul  2 19:12:18 C-I plasmashell[9858]:    at loadJsonFile (/app/Element/resources/app.asar/lib/utils.js:55:36)
Jul  2 19:12:18 C-I plasmashell[9858]:    at AppLocalization.fetchTranslationJson (/app/Element/resources/app.asar/lib/language-helper.js:83:45)
Jul  2 19:12:18 C-I plasmashell[9858]:    at /app/Element/resources/app.asar/lib/language-helper.js:96:39
Jul  2 19:12:18 C-I plasmashell[9858]:    at Array.filter (<anonymous>)
Jul  2 19:12:18 C-I plasmashell[9858]:    at AppLocalization.setAppLocale (/app/Element/resources/app.asar/lib/language-helper.js:95:39)
Jul  2 19:12:18 C-I plasmashell[9858]:    at new AppLocalization (/app/Element/resources/app.asar/lib/language-helper.js:65:18)
Jul  2 19:12:18 C-I plasmashell[9858]:    at /app/Element/resources/app.asar/lib/electron-main.js:530:30
Jul  2 19:12:18 C-I plasmashell[9858]:    at Generator.next (<anonymous>) {
Jul  2 19:12:18 C-I plasmashell[9858]:  code: 'ENOENT',
Jul  2 19:12:18 C-I plasmashell[9858]:  errno: -2
Jul  2 19:12:18 C-I plasmashell[9858]: }
Jul  2 19:12:18 C-I plasmashell[9858]: Resetting the UI components after locale change
Jul  2 19:12:18 C-I plasmashell[9858]: Resetting the UI components after locale change
Jul  2 19:12:18 C-I plasmashell[9916]: [51:0702/191218.252817:ERROR:gbm_pixmap_wayland.cc(82)] Cannot create bo with format= RGBA_8888 and usage=SCANOUT
Jul  2 19:12:18 C-I plasmashell[9916]: [51:0702/191218.252829:ERROR:gbm_pixmap_wayland.cc(82)] Cannot create bo with format= RGBA_8888 and usage=GPU_READ
Jul  2 19:12:18 C-I plasmashell[9916]: [51:0702/191218.252834:ERROR:shared_image_factory.cc(999)] CreateSharedImage: could not create backing.
Jul  2 19:12:18 C-I plasmashell[9916]: [51:0702/191218.252838:ERROR:shared_image_factory.cc(765)] DestroySharedImage: Could not find shared image mailbox
Jul  2 19:12:18 C-I plasmashell[9916]: [51:0702/191218.252856:ERROR:gpu_service_impl.cc(1124)] Exiting GPU process because some drivers can't recover from errors. GPU process will restart shortly.
Jul  2 19:12:18 C-I plasmashell[9858]: [3:0702/191218.257098:ERROR:gpu_process_host.cc(997)] GPU process exited unexpectedly: exit_code=8704
Jul  2 19:12:18 C-I plasmashell[9869]: [111:0702/191218.261662:ERROR:command_buffer_proxy_impl.cc(131)] ContextResult::kTransientFailure: Failed to send GpuControl.CreateCommandBuffer.
Jul  2 19:12:18 C-I plasmashell[9993]: [124:0702/191218.319023:ERROR:gbm_pixmap_wayland.cc(82)] Cannot create bo with format= RGBA_8888 and usage=SCANOUT
Jul  2 19:12:18 C-I plasmashell[9993]: [124:0702/191218.319034:ERROR:gbm_pixmap_wayland.cc(82)] Cannot create bo with format= RGBA_8888 and usage=GPU_READ
Jul  2 19:12:18 C-I plasmashell[9993]: [124:0702/191218.319038:ERROR:shared_image_factory.cc(999)] CreateSharedImage: could not create backing.
Jul  2 19:12:18 C-I plasmashell[9993]: [124:0702/191218.319041:ERROR:shared_image_factory.cc(765)] DestroySharedImage: Could not find shared image mailbox
Jul  2 19:12:18 C-I plasmashell[9993]: [124:0702/191218.319057:ERROR:gpu_service_impl.cc(1124)] Exiting GPU process because some drivers can't recover from errors. GPU process will restart shortly.
Jul  2 19:12:18 C-I plasmashell[9869]: [111:0702/191218.322276:ERROR:command_buffer_proxy_impl.cc(131)] ContextResult::kTransientFailure: Failed to send GpuControl.CreateCommandBuffer.
Jul  2 19:12:18 C-I plasmashell[9858]: [3:0702/191218.322876:ERROR:gpu_process_host.cc(997)] GPU process exited unexpectedly: exit_code=8704
Jul  2 19:12:18 C-I plasmashell[10036]: [167:0702/191218.382347:ERROR:gbm_pixmap_wayland.cc(82)] Cannot create bo with format= RGBA_8888 and usage=SCANOUT
Jul  2 19:12:18 C-I plasmashell[10036]: [167:0702/191218.382355:ERROR:gbm_pixmap_wayland.cc(82)] Cannot create bo with format= RGBA_8888 and usage=GPU_READ
Jul  2 19:12:18 C-I plasmashell[10036]: [167:0702/191218.382358:ERROR:shared_image_factory.cc(999)] CreateSharedImage: could not create backing.
Jul  2 19:12:18 C-I plasmashell[10036]: [167:0702/191218.382361:ERROR:shared_image_factory.cc(765)] DestroySharedImage: Could not find shared image mailbox
Jul  2 19:12:18 C-I plasmashell[10036]: [167:0702/191218.382377:ERROR:gpu_service_impl.cc(1124)] Exiting GPU process because some drivers can't recover from errors. GPU process will restart shortly.
Jul  2 19:12:18 C-I plasmashell[9869]: [111:0702/191218.385530:ERROR:command_buffer_proxy_impl.cc(131)] ContextResult::kTransientFailure: Failed to send GpuControl.CreateCommandBuffer.
Jul  2 19:12:18 C-I plasmashell[9858]: [3:0702/191218.386222:ERROR:gpu_process_host.cc(997)] GPU process exited unexpectedly: exit_code=8704
Jul  2 19:12:18 C-I plasmashell[9869]: [111:0702/191218.428999:ERROR:command_buffer_proxy_impl.cc(131)] ContextResult::kTransientFailure: Failed to send GpuControl.CreateCommandBuffer.
Jul  2 19:12:18 C-I plasmashell[9858]: Changing application language to de
Jul  2 19:12:18 C-I plasmashell[9858]: Fetching translation json for locale: de
Jul  2 19:12:18 C-I plasmashell[9858]: Could not fetch translation json for locale: 'de' Error: ENOENT, lib/i18n/strings/de.json not found in /app/Element/resources/app.asar
Jul  2 19:12:18 C-I plasmashell[9858]:    at createError (node:electron/js2c/node_init:2:1657)
Jul  2 19:12:18 C-I plasmashell[9858]:    at t.readFileSync (node:electron/js2c/node_init:2:9941)
Jul  2 19:12:18 C-I plasmashell[9858]:    at loadJsonFile (/app/Element/resources/app.asar/lib/utils.js:55:36)
Jul  2 19:12:18 C-I plasmashell[9858]:    at AppLocalization.fetchTranslationJson (/app/Element/resources/app.asar/lib/language-helper.js:83:45)
Jul  2 19:12:18 C-I plasmashell[9858]:    at /app/Element/resources/app.asar/lib/language-helper.js:96:39
Jul  2 19:12:18 C-I plasmashell[9858]:    at Array.filter (<anonymous>)
Jul  2 19:12:18 C-I plasmashell[9858]:    at AppLocalization.setAppLocale (/app/Element/resources/app.asar/lib/language-helper.js:95:39)
Jul  2 19:12:18 C-I plasmashell[9858]:    at IpcMainImpl.<anonymous> (/app/Element/resources/app.asar/lib/ipc.js:103:40)
Jul  2 19:12:18 C-I plasmashell[9858]:    at Generator.next (<anonymous>)
Jul  2 19:12:18 C-I plasmashell[9858]:    at /app/Element/resources/app.asar/lib/ipc.js:23:71 {
Jul  2 19:12:18 C-I plasmashell[9858]:  code: 'ENOENT',
Jul  2 19:12:18 C-I plasmashell[9858]:  errno: -2
Jul  2 19:12:18 C-I plasmashell[9858]: }
Jul  2 19:12:18 C-I plasmashell[9858]: Resetting the UI components after locale change

```

**Comment by corincorvus** [comment]
I resolved it with Flatseal and change the windowmanager to x11, disable wayland.
